/*
 * Copyright (c) 2015, msyksphinz
 * All rights reserved.
 *
 *   Redistribution and use in source and binary forms, with or without
 *   modification, are permitted provided that the following conditions are met:
 *   * Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *   * Neither the name of the copyright holder nor the
 *     names of its contributors may be used to endorse or promote products
 *     derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *   ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
 *   DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *   (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 *   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* CAUTION! THIS SOURCE CODE IS GENERATED AUTOMATICALLY. DON'T MODIFY BY HAND. */


#pragma once

enum class InstId_t : uint32_t {
    INST_ID_LUI = 0,
    INST_ID_AUIPC = 1,
    INST_ID_JAL = 2,
    INST_ID_JALR = 3,
    INST_ID_BEQ = 4,
    INST_ID_BNE = 5,
    INST_ID_BLT = 6,
    INST_ID_BGE = 7,
    INST_ID_BLTU = 8,
    INST_ID_BGEU = 9,
    INST_ID_LB = 10,
    INST_ID_LH = 11,
    INST_ID_LW = 12,
    INST_ID_LBU = 13,
    INST_ID_LHU = 14,
    INST_ID_SB = 15,
    INST_ID_SH = 16,
    INST_ID_SW = 17,
    INST_ID_ADDI = 18,
    INST_ID_SLTI = 19,
    INST_ID_SLTIU = 20,
    INST_ID_XORI = 21,
    INST_ID_ORI = 22,
    INST_ID_ANDI = 23,
    INST_ID_SLLI = 24,
    INST_ID_SRLI = 25,
    INST_ID_SRAI = 26,
    INST_ID_ADD = 27,
    INST_ID_SUB = 28,
    INST_ID_SLL = 29,
    INST_ID_SLT = 30,
    INST_ID_SLTU = 31,
    INST_ID_XOR = 32,
    INST_ID_SRL = 33,
    INST_ID_SRA = 34,
    INST_ID_OR = 35,
    INST_ID_AND = 36,
    INST_ID_FENCE = 37,
    INST_ID_FENCE_I = 38,
    INST_ID_MUL = 39,
    INST_ID_MULH = 40,
    INST_ID_MULHSU = 41,
    INST_ID_MULHU = 42,
    INST_ID_DIV = 43,
    INST_ID_DIVU = 44,
    INST_ID_REM = 45,
    INST_ID_REMU = 46,
    INST_ID_LR_W = 47,
    INST_ID_SC_W = 48,
    INST_ID_AMOSWAP_W = 49,
    INST_ID_AMOADD_W = 50,
    INST_ID_AMOXOR_W = 51,
    INST_ID_AMOAND_W = 52,
    INST_ID_AMOOR_W = 53,
    INST_ID_AMOMIN_W = 54,
    INST_ID_AMOMAX_W = 55,
    INST_ID_AMOMINU_W = 56,
    INST_ID_AMOMAXU_W = 57,
    INST_ID_FLW = 58,
    INST_ID_FSW = 59,
    INST_ID_FMADD_S = 60,
    INST_ID_FMSUB_S = 61,
    INST_ID_FNMSUB_S = 62,
    INST_ID_FNMADD_S = 63,
    INST_ID_FADD_S = 64,
    INST_ID_FSUB_S = 65,
    INST_ID_FMUL_S = 66,
    INST_ID_FDIV_S = 67,
    INST_ID_FSQRT_S = 68,
    INST_ID_FSGNJ_S = 69,
    INST_ID_FSGNJN_S = 70,
    INST_ID_FSGNJX_S = 71,
    INST_ID_FMIN_S = 72,
    INST_ID_FMAX_S = 73,
    INST_ID_FCVT_W_S = 74,
    INST_ID_FCVT_WU_S = 75,
    INST_ID_FMV_X_W = 76,
    INST_ID_FEQ_S = 77,
    INST_ID_FLT_S = 78,
    INST_ID_FLE_S = 79,
    INST_ID_FCLASS_S = 80,
    INST_ID_FCVT_S_W = 81,
    INST_ID_FCVT_S_WU = 82,
    INST_ID_FMV_W_X = 83,
    INST_ID_FLD = 84,
    INST_ID_FSD = 85,
    INST_ID_FMADD_D = 86,
    INST_ID_FMSUB_D = 87,
    INST_ID_FNMSUB_D = 88,
    INST_ID_FNMADD_D = 89,
    INST_ID_FADD_D = 90,
    INST_ID_FSUB_D = 91,
    INST_ID_FMUL_D = 92,
    INST_ID_FDIV_D = 93,
    INST_ID_FSQRT_D = 94,
    INST_ID_FSGNJ_D = 95,
    INST_ID_FSGNJN_D = 96,
    INST_ID_FSGNJX_D = 97,
    INST_ID_FMIN_D = 98,
    INST_ID_FMAX_D = 99,
    INST_ID_FCVT_S_D = 100,
    INST_ID_FCVT_D_S = 101,
    INST_ID_FEQ_D = 102,
    INST_ID_FLT_D = 103,
    INST_ID_FLE_D = 104,
    INST_ID_FCLASS_D = 105,
    INST_ID_FCVT_W_D = 106,
    INST_ID_FCVT_WU_D = 107,
    INST_ID_FCVT_D_W = 108,
    INST_ID_FCVT_D_WU = 109,
    INST_ID_CSRRW = 110,
    INST_ID_CSRRS = 111,
    INST_ID_CSRRC = 112,
    INST_ID_CSRRWI = 113,
    INST_ID_CSRRSI = 114,
    INST_ID_CSRRCI = 115,
    INST_ID_ECALL = 116,
    INST_ID_EBREAK = 117,
    INST_ID_URET = 118,
    INST_ID_SRET = 119,
    INST_ID_HRET = 120,
    INST_ID_MRET = 121,
    INST_ID_MRTS = 122,
    INST_ID_MRTH = 123,
    INST_ID_WFI = 124,
    INST_ID_SFENCE_VMA = 125,
    INST_ID_LWU = 126,
    INST_ID_LD = 127,
    INST_ID_SD = 128,
    INST_ID_ADDIW = 129,
    INST_ID_SLLIW = 130,
    INST_ID_SRLIW = 131,
    INST_ID_SRAIW = 132,
    INST_ID_ADDW = 133,
    INST_ID_SUBW = 134,
    INST_ID_SLLW = 135,
    INST_ID_SRLW = 136,
    INST_ID_SRAW = 137,
    INST_ID_MULW = 138,
    INST_ID_DIVW = 139,
    INST_ID_DIVUW = 140,
    INST_ID_REMW = 141,
    INST_ID_REMUW = 142,
    INST_ID_LR_D = 143,
    INST_ID_SC_D = 144,
    INST_ID_AMOSWAP_D = 145,
    INST_ID_AMOADD_D = 146,
    INST_ID_AMOXOR_D = 147,
    INST_ID_AMOAND_D = 148,
    INST_ID_AMOOR_D = 149,
    INST_ID_AMOMIN_D = 150,
    INST_ID_AMOMAX_D = 151,
    INST_ID_AMOMINU_D = 152,
    INST_ID_AMOMAXU_D = 153,
    INST_ID_FCVT_L_S = 154,
    INST_ID_FCVT_LU_S = 155,
    INST_ID_FCVT_S_L = 156,
    INST_ID_FCVT_S_LU = 157,
    INST_ID_FCVT_L_D = 158,
    INST_ID_FCVT_LU_D = 159,
    INST_ID_FMV_X_D = 160,
    INST_ID_FCVT_D_L = 161,
    INST_ID_FCVT_D_LU = 162,
    INST_ID_FMV_D_X = 163,
    INST_ID_C_ADDI4SPN = 164,
    INST_ID_C_FLD = 165,
    INST_ID_C_LW = 166,
    INST_ID_C_FLW = 167,
    INST_ID_C_LD = 168,
    INST_ID_C_FSD = 169,
    INST_ID_C_SW = 170,
    INST_ID_C_FSW = 171,
    INST_ID_C_SD = 172,
    INST_ID_C_NOP = 173,
    INST_ID_C_ADDI = 174,
    INST_ID_C_JAL = 175,
    INST_ID_C_ADDIW = 176,
    INST_ID_C_LI = 177,
    INST_ID_C_ADDI16SP = 178,
    INST_ID_C_LUI = 179,
    INST_ID_C_SRLI = 180,
    INST_ID_C_SRLI64 = 181,
    INST_ID_C_SRAI = 182,
    INST_ID_C_SRAI64 = 183,
    INST_ID_C_ANDI = 184,
    INST_ID_C_SUB = 185,
    INST_ID_C_XOR = 186,
    INST_ID_C_OR = 187,
    INST_ID_C_AND = 188,
    INST_ID_C_SUBW = 189,
    INST_ID_C_ADDW = 190,
    INST_ID_C_J = 191,
    INST_ID_C_BEQZ = 192,
    INST_ID_C_BNEZ = 193,
    INST_ID_C_SLLI = 194,
    INST_ID_C_FLDSP = 195,
    INST_ID_C_LWSP = 196,
    INST_ID_C_FLWSP = 197,
    INST_ID_C_LDSP = 198,
    INST_ID_C_JR = 199,
    INST_ID_C_MV = 200,
    INST_ID_C_EBREAK = 201,
    INST_ID_C_JALR = 202,
    INST_ID_C_ADD = 203,
    INST_ID_C_FSDSP = 204,
    INST_ID_C_SWSP = 205,
    INST_ID_C_FSWSP = 206,
    INST_ID_C_SDSP = 207,
    INST_ID_SENTINEL_MAX = 208
};
