/*
 * Copyright (c) 2015, msyksphinz
 * All rights reserved.
 *
 *   Redistribution and use in source and binary forms, with or without
 *   modification, are permitted provided that the following conditions are met:
 *   * Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *   * Neither the name of the copyright holder nor the
 *     names of its contributors may be used to endorse or promote products
 *     derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *   ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
 *   DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *   (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 *   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* CAUTION! THIS SOURCE CODE IS GENERATED AUTOMATICALLY. DON'T MODIFY BY HAND. */


#include <string>
#include "inst_riscv.hpp"
const InstEnv::InstFunc InstEnv::m_inst_exec_func[] = {
  &InstEnv::RISCV_INST_LUI,
  &InstEnv::RISCV_INST_AUIPC,
  &InstEnv::RISCV_INST_JAL,
  &InstEnv::RISCV_INST_JALR,
  &InstEnv::RISCV_INST_BEQ,
  &InstEnv::RISCV_INST_BNE,
  &InstEnv::RISCV_INST_BLT,
  &InstEnv::RISCV_INST_BGE,
  &InstEnv::RISCV_INST_BLTU,
  &InstEnv::RISCV_INST_BGEU,
  &InstEnv::RISCV_INST_LB,
  &InstEnv::RISCV_INST_LH,
  &InstEnv::RISCV_INST_LW,
  &InstEnv::RISCV_INST_LBU,
  &InstEnv::RISCV_INST_LHU,
  &InstEnv::RISCV_INST_SB,
  &InstEnv::RISCV_INST_SH,
  &InstEnv::RISCV_INST_SW,
  &InstEnv::RISCV_INST_ADDI,
  &InstEnv::RISCV_INST_SLTI,
  &InstEnv::RISCV_INST_SLTIU,
  &InstEnv::RISCV_INST_XORI,
  &InstEnv::RISCV_INST_ORI,
  &InstEnv::RISCV_INST_ANDI,
  &InstEnv::RISCV_INST_SLLI,
  &InstEnv::RISCV_INST_SRLI,
  &InstEnv::RISCV_INST_SRAI,
  &InstEnv::RISCV_INST_ADD,
  &InstEnv::RISCV_INST_SUB,
  &InstEnv::RISCV_INST_SLL,
  &InstEnv::RISCV_INST_SLT,
  &InstEnv::RISCV_INST_SLTU,
  &InstEnv::RISCV_INST_XOR,
  &InstEnv::RISCV_INST_SRL,
  &InstEnv::RISCV_INST_SRA,
  &InstEnv::RISCV_INST_OR,
  &InstEnv::RISCV_INST_AND,
  &InstEnv::RISCV_INST_FENCE,
  &InstEnv::RISCV_INST_FENCE_I,
  &InstEnv::RISCV_INST_MUL,
  &InstEnv::RISCV_INST_MULH,
  &InstEnv::RISCV_INST_MULHSU,
  &InstEnv::RISCV_INST_MULHU,
  &InstEnv::RISCV_INST_DIV,
  &InstEnv::RISCV_INST_DIVU,
  &InstEnv::RISCV_INST_REM,
  &InstEnv::RISCV_INST_REMU,
  &InstEnv::RISCV_INST_LR_W,
  &InstEnv::RISCV_INST_SC_W,
  &InstEnv::RISCV_INST_AMOSWAP_W,
  &InstEnv::RISCV_INST_AMOADD_W,
  &InstEnv::RISCV_INST_AMOXOR_W,
  &InstEnv::RISCV_INST_AMOAND_W,
  &InstEnv::RISCV_INST_AMOOR_W,
  &InstEnv::RISCV_INST_AMOMIN_W,
  &InstEnv::RISCV_INST_AMOMAX_W,
  &InstEnv::RISCV_INST_AMOMINU_W,
  &InstEnv::RISCV_INST_AMOMAXU_W,
  &InstEnv::RISCV_INST_FLW,
  &InstEnv::RISCV_INST_FSW,
  &InstEnv::RISCV_INST_FMADD_S,
  &InstEnv::RISCV_INST_FMSUB_S,
  &InstEnv::RISCV_INST_FNMSUB_S,
  &InstEnv::RISCV_INST_FNMADD_S,
  &InstEnv::RISCV_INST_FADD_S,
  &InstEnv::RISCV_INST_FSUB_S,
  &InstEnv::RISCV_INST_FMUL_S,
  &InstEnv::RISCV_INST_FDIV_S,
  &InstEnv::RISCV_INST_FSQRT_S,
  &InstEnv::RISCV_INST_FSGNJ_S,
  &InstEnv::RISCV_INST_FSGNJN_S,
  &InstEnv::RISCV_INST_FSGNJX_S,
  &InstEnv::RISCV_INST_FMIN_S,
  &InstEnv::RISCV_INST_FMAX_S,
  &InstEnv::RISCV_INST_FCVT_W_S,
  &InstEnv::RISCV_INST_FCVT_WU_S,
  &InstEnv::RISCV_INST_FMV_X_W,
  &InstEnv::RISCV_INST_FEQ_S,
  &InstEnv::RISCV_INST_FLT_S,
  &InstEnv::RISCV_INST_FLE_S,
  &InstEnv::RISCV_INST_FCLASS_S,
  &InstEnv::RISCV_INST_FCVT_S_W,
  &InstEnv::RISCV_INST_FCVT_S_WU,
  &InstEnv::RISCV_INST_FMV_W_X,
  &InstEnv::RISCV_INST_FLD,
  &InstEnv::RISCV_INST_FSD,
  &InstEnv::RISCV_INST_FMADD_D,
  &InstEnv::RISCV_INST_FMSUB_D,
  &InstEnv::RISCV_INST_FNMSUB_D,
  &InstEnv::RISCV_INST_FNMADD_D,
  &InstEnv::RISCV_INST_FADD_D,
  &InstEnv::RISCV_INST_FSUB_D,
  &InstEnv::RISCV_INST_FMUL_D,
  &InstEnv::RISCV_INST_FDIV_D,
  &InstEnv::RISCV_INST_FSQRT_D,
  &InstEnv::RISCV_INST_FSGNJ_D,
  &InstEnv::RISCV_INST_FSGNJN_D,
  &InstEnv::RISCV_INST_FSGNJX_D,
  &InstEnv::RISCV_INST_FMIN_D,
  &InstEnv::RISCV_INST_FMAX_D,
  &InstEnv::RISCV_INST_FCVT_S_D,
  &InstEnv::RISCV_INST_FCVT_D_S,
  &InstEnv::RISCV_INST_FEQ_D,
  &InstEnv::RISCV_INST_FLT_D,
  &InstEnv::RISCV_INST_FLE_D,
  &InstEnv::RISCV_INST_FCLASS_D,
  &InstEnv::RISCV_INST_FCVT_W_D,
  &InstEnv::RISCV_INST_FCVT_WU_D,
  &InstEnv::RISCV_INST_FCVT_D_W,
  &InstEnv::RISCV_INST_FCVT_D_WU,
  &InstEnv::RISCV_INST_CSRRW,
  &InstEnv::RISCV_INST_CSRRS,
  &InstEnv::RISCV_INST_CSRRC,
  &InstEnv::RISCV_INST_CSRRWI,
  &InstEnv::RISCV_INST_CSRRSI,
  &InstEnv::RISCV_INST_CSRRCI,
  &InstEnv::RISCV_INST_ECALL,
  &InstEnv::RISCV_INST_EBREAK,
  &InstEnv::RISCV_INST_URET,
  &InstEnv::RISCV_INST_SRET,
  &InstEnv::RISCV_INST_HRET,
  &InstEnv::RISCV_INST_MRET,
  &InstEnv::RISCV_INST_MRTS,
  &InstEnv::RISCV_INST_MRTH,
  &InstEnv::RISCV_INST_WFI,
  &InstEnv::RISCV_INST_SFENCE_VMA,
  &InstEnv::RISCV_INST_LWU,
  &InstEnv::RISCV_INST_LD,
  &InstEnv::RISCV_INST_SD,
  &InstEnv::RISCV_INST_ADDIW,
  &InstEnv::RISCV_INST_SLLIW,
  &InstEnv::RISCV_INST_SRLIW,
  &InstEnv::RISCV_INST_SRAIW,
  &InstEnv::RISCV_INST_ADDW,
  &InstEnv::RISCV_INST_SUBW,
  &InstEnv::RISCV_INST_SLLW,
  &InstEnv::RISCV_INST_SRLW,
  &InstEnv::RISCV_INST_SRAW,
  &InstEnv::RISCV_INST_MULW,
  &InstEnv::RISCV_INST_DIVW,
  &InstEnv::RISCV_INST_DIVUW,
  &InstEnv::RISCV_INST_REMW,
  &InstEnv::RISCV_INST_REMUW,
  &InstEnv::RISCV_INST_LR_D,
  &InstEnv::RISCV_INST_SC_D,
  &InstEnv::RISCV_INST_AMOSWAP_D,
  &InstEnv::RISCV_INST_AMOADD_D,
  &InstEnv::RISCV_INST_AMOXOR_D,
  &InstEnv::RISCV_INST_AMOAND_D,
  &InstEnv::RISCV_INST_AMOOR_D,
  &InstEnv::RISCV_INST_AMOMIN_D,
  &InstEnv::RISCV_INST_AMOMAX_D,
  &InstEnv::RISCV_INST_AMOMINU_D,
  &InstEnv::RISCV_INST_AMOMAXU_D,
  &InstEnv::RISCV_INST_FCVT_L_S,
  &InstEnv::RISCV_INST_FCVT_LU_S,
  &InstEnv::RISCV_INST_FCVT_S_L,
  &InstEnv::RISCV_INST_FCVT_S_LU,
  &InstEnv::RISCV_INST_FCVT_L_D,
  &InstEnv::RISCV_INST_FCVT_LU_D,
  &InstEnv::RISCV_INST_FMV_X_D,
  &InstEnv::RISCV_INST_FCVT_D_L,
  &InstEnv::RISCV_INST_FCVT_D_LU,
  &InstEnv::RISCV_INST_FMV_D_X,
  &InstEnv::RISCV_INST_C_ADDI4SPN,
  &InstEnv::RISCV_INST_C_FLD,
  &InstEnv::RISCV_INST_C_LW,
  &InstEnv::RISCV_INST_C_FLW,
  &InstEnv::RISCV_INST_C_LD,
  &InstEnv::RISCV_INST_C_FSD,
  &InstEnv::RISCV_INST_C_SW,
  &InstEnv::RISCV_INST_C_FSW,
  &InstEnv::RISCV_INST_C_SD,
  &InstEnv::RISCV_INST_C_NOP,
  &InstEnv::RISCV_INST_C_ADDI,
  &InstEnv::RISCV_INST_C_JAL,
  &InstEnv::RISCV_INST_C_ADDIW,
  &InstEnv::RISCV_INST_C_LI,
  &InstEnv::RISCV_INST_C_ADDI16SP,
  &InstEnv::RISCV_INST_C_LUI,
  &InstEnv::RISCV_INST_C_SRLI,
  &InstEnv::RISCV_INST_C_SRLI64,
  &InstEnv::RISCV_INST_C_SRAI,
  &InstEnv::RISCV_INST_C_SRAI64,
  &InstEnv::RISCV_INST_C_ANDI,
  &InstEnv::RISCV_INST_C_SUB,
  &InstEnv::RISCV_INST_C_XOR,
  &InstEnv::RISCV_INST_C_OR,
  &InstEnv::RISCV_INST_C_AND,
  &InstEnv::RISCV_INST_C_SUBW,
  &InstEnv::RISCV_INST_C_ADDW,
  &InstEnv::RISCV_INST_C_J,
  &InstEnv::RISCV_INST_C_BEQZ,
  &InstEnv::RISCV_INST_C_BNEZ,
  &InstEnv::RISCV_INST_C_SLLI,
  &InstEnv::RISCV_INST_C_FLDSP,
  &InstEnv::RISCV_INST_C_LWSP,
  &InstEnv::RISCV_INST_C_FLWSP,
  &InstEnv::RISCV_INST_C_LDSP,
  &InstEnv::RISCV_INST_C_JR,
  &InstEnv::RISCV_INST_C_MV,
  &InstEnv::RISCV_INST_C_EBREAK,
  &InstEnv::RISCV_INST_C_JALR,
  &InstEnv::RISCV_INST_C_ADD,
  &InstEnv::RISCV_INST_C_FSDSP,
  &InstEnv::RISCV_INST_C_SWSP,
  &InstEnv::RISCV_INST_C_FSWSP,
  &InstEnv::RISCV_INST_C_SDSP
  };
