/*
 * Copyright (c) 2015, msyksphinz
 * All rights reserved.
 *
 *   Redistribution and use in source and binary forms, with or without
 *   modification, are permitted provided that the following conditions are met:
 *   * Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *   * Neither the name of the copyright holder nor the
 *     names of its contributors may be used to endorse or promote products
 *     derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *   ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
 *   DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *   (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 *   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* CAUTION! THIS SOURCE CODE IS GENERATED AUTOMATICALLY. DON'T MODIFY BY HAND. */


#include <string>
#include "inst_list_riscv.hpp"
#include "dec_utils_riscv.hpp"


const char *inst_strings[209] = {
  "lui        @,@",
  "auipc      @,@",
  "jal        @,@",
  "jalr       @,@,@",
  "beq        @,@,@<<1",
  "bne        @,@,@<<1",
  "blt        @,@,@<<1",
  "bge        @,@,@<<1",
  "bltu       @,@,@<<1",
  "bgeu       @,@,@<<1",
  "lb         @,@(@)",
  "lh         @,@(@)",
  "lw         @,@(@)",
  "lbu        @,@(@)",
  "lhu        @,@(@)",
  "sb         @,@(@)",
  "sh         @,@(@)",
  "sw         @,@(@)",
  "addi       @,@,@",
  "slti       @,@,@",
  "sltiu      @,@,@",
  "xori       @,@,@",
  "ori        @,@,@",
  "andi       @,@,@",
  "slli       @,@,@",
  "srli       @,@,@",
  "srai       @,@,@",
  "add        @,@,@",
  "sub        @,@,@",
  "sll        @,@,@",
  "slt        @,@,@",
  "sltu       @,@,@",
  "xor        @,@,@",
  "srl        @,@,@",
  "sra        @,@,@",
  "or         @,@,@",
  "and        @,@,@",
  "fence",
  "fence.i",
  "mul        @,@,@",
  "mulh       @,@,@",
  "mulhsu     @,@,@",
  "mulhu      @,@,@",
  "div        @,@,@",
  "divu       @,@,@",
  "rem        @,@,@",
  "remu       @,@,@",
  "lr.w       @,@",
  "sc.w       @,@,@",
  "amoswap.w  @,@,(@)",
  "amoadd.w   @,@,(@)",
  "amoxor.w   @,@,(@)",
  "amoand.w   @,@,(@)",
  "amoor.w    @,@,(@)",
  "amomin.w   @,@,(@)",
  "amomax.w   @,@,(@)",
  "amominu.w  @,@,(@)",
  "amomaxu.w  @,@,(@)",
  "flw        @,@(@)",
  "fsw        @,@(@)",
  "fmadd.s    @,@,@,@",
  "fmsub.s    @,@,@,@",
  "fnmsub.s   @,@,@,@",
  "fnmadd.s   @,@,@,@",
  "fadd.s     @,@,@",
  "fsub.s     @,@,@",
  "fmul.s     @,@,@",
  "fdiv.s     @,@,@",
  "fsqrt.s    @,@",
  "fsgnj.s    @,@,@",
  "fsgnjn.s   @,@,@",
  "fsgnjx.s   @,@,@",
  "fmin.s     @,@,@",
  "fmax.s     @,@,@",
  "fcvt.w.s   @,@",
  "fcvt.wu.s  @,@",
  "fmv.x.w    @,@",
  "feq.s      @,@,@",
  "flt.s      @,@,@",
  "fle.s      @,@,@",
  "fclass.s   @,@",
  "fcvt.s.w   @,@",
  "fcvt.s.wu  @,@",
  "fmv.w.x    @,@",
  "fld        @,@,@",
  "fsd        @,@(@)",
  "fmadd.d    @,@,@,@",
  "fmsub.d    @,@,@,@",
  "fnmsub.d   @,@,@,@",
  "fnmadd.d   @,@,@,@",
  "fadd.d     @,@,@",
  "fsub.d     @,@,@",
  "fmul.d     @,@,@",
  "fdiv.d     @,@,@",
  "fsqrt.d    @,@",
  "fsgnj.d    @,@,@",
  "fsgnjn.d   @,@,@",
  "fsgnjx.d   @,@,@",
  "fmin.d     @,@,@",
  "fmax.d     @,@,@",
  "fcvt.s.d   @,@",
  "fcvt.d.s   @,@",
  "feq.d      @,@,@",
  "flt.d      @,@,@",
  "fle.d      @,@,@",
  "fclass.d   @,@",
  "fcvt.w.d   @,@",
  "fcvt.wu.d  @,@",
  "fcvt.d.w   @,@",
  "fcvt.d.wu  @,@",
  "csrrw      @,@,@",
  "csrrs      @,@,@",
  "csrrc      @,@,@",
  "csrrwi     @,@,@",
  "csrrsi     @,@,@",
  "csrrci     @,@,@",
  "ecall",
  "ebreak",
  "uret",
  "sret",
  "hret",
  "mret",
  "mrts",
  "mrth",
  "wfi",
  "sfence.vma @,@",
  "lwu        @,@(@)",
  "ld         @,@(@)",
  "sd         @,@(@)",
  "addiw      @,@,@",
  "slliw      @,@,@",
  "srliw      @,@,@",
  "sraiw      @,@,@",
  "addw       @,@,@",
  "subw       @,@,@",
  "sllw       @,@,@",
  "srlw       @,@,@",
  "sraw       @,@,@",
  "mulw       @,@,@",
  "divw       @,@,@",
  "divuw      @,@,@",
  "remw       @,@,@",
  "remuw      @,@,@",
  "lr.d       @,@",
  "sc.d       @,@,@",
  "amoswap.d  @,@,(@)",
  "amoadd.d   @,@,(@)",
  "amoxor.d   @,@,(@)",
  "amoand.d   @,@,(@)",
  "amoor.d    @,@,(@)",
  "amomin.d   @,@,(@)",
  "amomax.d   @,@,(@)",
  "amominu.d  @,@,(@)",
  "amomaxu.d  @,@,(@)",
  "fcvt.l.s   @,@",
  "fcvt.lu.s  @,@",
  "fcvt.s.l   @,@",
  "fcvt.s.lu  @,@",
  "fcvt.l.d   @,@",
  "fcvt.lu.d  @,@",
  "fmv.x.d    @,@",
  "fcvt.d.l   @,@",
  "fcvt.d.lu  @,@",
  "fmv.d.x    @,@",
  "c.addi4spn @,@",
  "c.fld      @,@,@<<3",
  "c.lw       @,@,@<<2",
  "c.flw      @,@,@<<2",
  "c.ld       @,@,@<<3",
  "c.fsd      @,@,@<<3",
  "c.sw       @,@,@<<2",
  "c.fsw      @,@,@<<2",
  "c.sd       @,@,@<<3",
  "c.nop     ",
  "c.addi     @,@",
  "c.jal      @<<1",
  "c.addiw    @,@",
  "c.li       @,@",
  "c.addi16sp @,@",
  "c.lui      @,@",
  "c.srli     @,@",
  "c.srli64   @,@",
  "c.srai     @,@",
  "c.srai64   @,@",
  "c.andi     @,@",
  "c.sub      @,@",
  "c.xor      @,@",
  "c.or       @,@",
  "c.and      @,@",
  "c.subw     @,@",
  "c.addw     @,@",
  "c.j        @<<1",
  "c.beqz     @,@<<1",
  "c.bnez     @,@<<1",
  "c.slli     @,@",
  "c.fldsp    @,@<<3 ",
  "c.lwsp     @,@<<2",
  "c.flwsp    @,@<<2",
  "c.ldsp     @,@<<3",
  "c.jr       @",
  "c.mv       @,@",
  "c.ebreak  ",
  "c.jalr     @",
  "c.add      @,@",
  "c.fsdsp    @,@<<3",
  "c.swsp     @,@<<2",
  "c.fswsp    @,@<<3",
  "c.sdsp     @,@<<3",
"<Unknown Inst>"
};
